-- Tabela NPC — wersja PostgreSQL (konwersja z SQL Server)
-- Nazwy zostawione UPPERCASE jak w oryginale, ale BEZ cudzysłowów.
-- Postgres zapisze je fizycznie jako lowercase, a odwołania pisane UPPERCASE
-- (też bez cudzysłowów) działają — bo Postgres zwija obie strony do małych liter.
-- WAŻNE: nigdy nie cytuj nazw ("NPC_ID_...") w kodzie, bo wtedy wymusisz cudzysłowy WSZĘDZIE.

CREATE TABLE NPC (
  NPC_ID_MOJE_PK  BIGINT GENERATED BY DEFAULT AS IDENTITY,
  NPC_ID_Z_GRY    BIGINT,

  NAZWA  VARCHAR(255) NOT NULL UNIQUE,
  PLEC   VARCHAR(5),
  RASA   VARCHAR(255),
  KLASA  VARCHAR(255),
  TYTUL  VARCHAR(255),

  ZRODLO_NAZWA VARCHAR(20) NOT NULL
    CHECK (ZRODLO_NAZWA IN ('wiki', 'wowhead', 'wowdb', 'recznie', 'z addonu')),

  DATA_DODANIA TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT PK_NPC PRIMARY KEY (NPC_ID_MOJE_PK)
);
