from scraper_wowhead_metadane import buduj_mapping_01

# OSTATNIE REVIEW: 21.01.2026

# POBIERA LINKI DO WOWHEADA Z BAZY DANYCH, A NASTĘPNIE JE SCRAPUJE W POSZUKIWANIU KRAINY, DODATKU ITP. 
buduj_mapping_01()

# JAK SKOŃCZY SIĘ WYKONYWAĆ SKRYPT, WEJŚĆ DO PLIKU I PRZESUNĄĆ W DÓŁ FORMUŁY & DODAĆ TŁUMACZENIA W BRAKACH