from moduly.etl_excel import slowa_kluczowe_do_db

# OSTATNIE REVIEW: 22.01.2026

# PONIZSZA FUNKCJA ZAPISUJE DANE DO TABELI dbo.SLOWA_KLUCZOWE
# DODAJE TYLKO TE KTORYCH NIE ZNAJDZIE
# W PRZYPADKU WYKRYTYCH ZMIAN W TLUMACZENIACH, ROBI UPDATE
# NAJPIERW PRZYGOTOWAĆ EXCELA 
slowa_kluczowe_do_db()