from moduly.etl_excel import mapowanie_misji_do_db

# OSTATNIE REVIEW: 22.01.2026

# PONIZSZA FUNKCJA ZAPISUJE DANE DO TABELI dbo.MISJE_SLOWA_KLUCZOWE
# DODAJE TYLKO NOWE REKORDY
# NAJPIERW PRZYGOTOWAĆ EXCELA (TEN SAM CO W 02)
mapowanie_misji_do_db()