ALTER TABLE dbo.MISJE_LORE_PYTANIA
    ADD DATA_UPDATE DATETIME2(0) NULL;
GO

CREATE TRIGGER trg_MISJE_LORE_PYTANIA_DATAUPDATE
ON dbo.MISJE_LORE_PYTANIA
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE p
    SET DATA_UPDATE = SYSDATETIME()
    FROM dbo.MISJE_LORE_PYTANIA AS p
    INNER JOIN inserted AS i
        ON p.TECH_ID = i.TECH_ID;
END
GO
