SELECT
    COALESCE(SUM(INPUT_TOKENS_PRICE), 0)  AS INP,
    COALESCE(SUM(OUTPUT_TOKENS_PRICE), 0) AS OUTP,
    COALESCE(SUM(INPUT_TOKENS_PRICE), 0)
      + COALESCE(SUM(OUTPUT_TOKENS_PRICE), 0) AS RAZEM
FROM [WoW_PL].[dbo].[AI_LOGI]
WHERE CREATED_AT >= '2026-07-11'
  AND CREATED_AT <  '2026-07-12'
  AND STAGE = 'quest_summary';