USE WoW_PL;

WITH misje_lf AS (
    SELECT m.MISJA_ID_MOJE_PK, m.MISJA_TYTUL_EN,
           m.NAZWA_LINII_FABULARNEJ_EN, m.KOLEJNOSC_LINII_FABULARNEJ
    FROM dbo.MISJE AS m
    WHERE m.NAZWA_LINII_FABULARNEJ_EN IN
          (N'Ripple Effects', N'Dawn of Reckoning', N'Path of de Hash''ey')
),
npc_ids AS (
    SELECT mlf.MISJA_ID_MOJE_PK, v.ID_NPC
    FROM misje_lf AS mlf
    INNER JOIN dbo.MISJE AS m 
      ON m.MISJA_ID_MOJE_PK = mlf.MISJA_ID_MOJE_PK
    CROSS APPLY (VALUES (m.NPC_START_ID), (m.NPC_KONIEC_ID)) AS v(ID_NPC)
    WHERE v.ID_NPC IS NOT NULL
    UNION
    SELECT ds.MISJA_ID_MOJE_FK, ds.NPC_ID_FK
    FROM dbo.DIALOGI_STATUSY AS ds
    INNER JOIN misje_lf AS mlf 
      ON mlf.MISJA_ID_MOJE_PK = ds.MISJA_ID_MOJE_FK
    WHERE ds.NPC_ID_FK IS NOT NULL
),
npc_nazwy AS (
    SELECT ni.MISJA_ID_MOJE_PK,
           CASE WHEN CHARINDEX('[', ns.NAZWA) > 0
                THEN RTRIM(LEFT(ns.NAZWA, CHARINDEX('[', ns.NAZWA) - 1))
                ELSE ns.NAZWA END AS NPC_NAZWA
    FROM npc_ids AS ni
    INNER JOIN dbo.NPC_STATUSY AS ns
      ON ns.NPC_ID_FK = ni.ID_NPC
     AND ns.STATUS = N'0_ORYGINAŁ'
),
sk AS (
    SELECT msk.MISJA_ID_MOJE_FK, s.SLOWO_EN, s.SLOWO_PL
    FROM dbo.MISJE_SLOWA_KLUCZOWE AS msk
    INNER JOIN dbo.SLOWA_KLUCZOWE AS s 
      ON s.SLOWO_ID_PK = msk.SLOWO_ID
)
SELECT
    mlf.NAZWA_LINII_FABULARNEJ_EN          AS LINIA_FABULARNA,
    mlf.KOLEJNOSC_LINII_FABULARNEJ         AS KOLEJNOSC,
    mlf.MISJA_ID_MOJE_PK                   AS MISJA_ID,
    mlf.MISJA_TYTUL_EN                     AS TYTUL_EN,
    (SELECT STRING_AGG(x.NPC_NAZWA, N' | ')
     FROM (SELECT DISTINCT NPC_NAZWA FROM npc_nazwy
           WHERE MISJA_ID_MOJE_PK = mlf.MISJA_ID_MOJE_PK) AS x)            AS NPC,
    (SELECT STRING_AGG(CONCAT(y.SLOWO_EN, N' -> ', y.SLOWO_PL), N' | ')
     FROM (SELECT DISTINCT SLOWO_EN, SLOWO_PL FROM sk
           WHERE MISJA_ID_MOJE_FK = mlf.MISJA_ID_MOJE_PK) AS y)           AS SLOWA_KLUCZOWE
FROM misje_lf AS mlf
ORDER BY mlf.NAZWA_LINII_FABULARNEJ_EN, mlf.KOLEJNOSC_LINII_FABULARNEJ, mlf.MISJA_ID_MOJE_PK;