USE WoW_PL;

SELECT DISTINCT
    s.SLOWO_EN,
    s.SLOWO_PL
FROM dbo.MISJE AS m
INNER JOIN dbo.MISJE_SLOWA_KLUCZOWE AS msk
  ON msk.MISJA_ID_MOJE_FK = m.MISJA_ID_MOJE_PK
INNER JOIN dbo.SLOWA_KLUCZOWE AS s
  ON s.SLOWO_ID_PK = msk.SLOWO_ID
WHERE m.DODATEK_EN = N'The War Within'
ORDER BY s.SLOWO_EN;