DECLARE @dodatek NVARCHAR(30) = N'Midnight';

WITH MISJE AS (
    SELECT
        m.MISJA_ID_MOJE_PK
    FROM dbo.MISJE AS m
    WHERE m.DODATEK_EN = @dodatek
      AND m.NAZWA_LINII_FABULARNEJ_EN IN ('Path of de Hash''ey')
),

NPC_MISJE AS (
    SELECT DISTINCT
        mm.MISJA_ID_MOJE_PK AS MISJA_ID,
        v.NPC_ID
    FROM MISJE AS mm
    INNER JOIN dbo.MISJE AS m
        ON m.MISJA_ID_MOJE_PK = mm.MISJA_ID_MOJE_PK
    CROSS APPLY (
        VALUES
            (m.NPC_START_ID),
            (m.NPC_KONIEC_ID)
    ) AS v(NPC_ID)
    WHERE v.NPC_ID IS NOT NULL

    UNION

    SELECT DISTINCT
        ds.MISJA_ID_MOJE_FK AS MISJA_ID,
        ds.NPC_ID_FK AS NPC_ID
    FROM dbo.DIALOGI_STATUSY AS ds
    INNER JOIN MISJE AS mm
        ON mm.MISJA_ID_MOJE_PK = ds.MISJA_ID_MOJE_FK
    WHERE ds.STATUS = N'0_ORYGINAŁ'
),

STATYSTYKA_NPC AS (
    SELECT
        nwm.NPC_ID,
        COUNT(DISTINCT nwm.MISJA_ID) AS ILE_MISJI
    FROM NPC_MISJE AS nwm
    GROUP BY nwm.NPC_ID
),

DIALOGI_NPC AS (
    SELECT
        ds.NPC_ID_FK AS NPC_ID,
        COUNT(*) AS ILE_WYPOWIEDZI_W_DIALOGACH
    FROM dbo.DIALOGI_STATUSY AS ds
    INNER JOIN MISJE AS mm
        ON mm.MISJA_ID_MOJE_PK = ds.MISJA_ID_MOJE_FK
    WHERE ds.STATUS = N'0_ORYGINAŁ'
    GROUP BY ds.NPC_ID_FK
)

SELECT
    sn.NPC_ID AS ID,
    n.NAZWA,
    COALESCE(NULLIF(LTRIM(RTRIM(n.RASA)), N''), N'Brak danych') AS RASA,
    sn.ILE_MISJI,
    COALESCE(dn.ILE_WYPOWIEDZI_W_DIALOGACH, 0) AS ILE_WYPOWIEDZI_W_DIALOGACH
FROM STATYSTYKA_NPC AS sn
INNER JOIN dbo.NPC AS n
    ON n.NPC_ID_MOJE_PK = sn.NPC_ID
LEFT JOIN DIALOGI_NPC AS dn
    ON dn.NPC_ID = sn.NPC_ID
--WHERE n.NAZWA = N'Gnarldin'
ORDER BY
    sn.ILE_MISJI DESC,
    ILE_WYPOWIEDZI_W_DIALOGACH DESC,
    n.NAZWA;
