-- TOTAL NA DODATEK/FABULA/KRAINA
SELECT DISTINCT
	DODATEK_EN, NAZWA_LINII_FABULARNEJ_EN, KRAINA_EN
FROM dbo.MISJE AS M
INNER JOIN dbo.ARCHIWUM_MISJE_DIALOGI AS AMD
  ON M.MISJA_ID_Z_GRY = AMD.MISJA_ID_Z_GRY
;

-- COUNT NA FABULA
SELECT
	M.NAZWA_LINII_FABULARNEJ_EN, COUNT(DISTINCT M.MISJA_ID_Z_GRY) AS CNT
FROM dbo.MISJE AS M
INNER JOIN dbo.ARCHIWUM_MISJE_DIALOGI AS AMD
  ON M.MISJA_ID_Z_GRY = AMD.MISJA_ID_Z_GRY
WHERE 1=1
  AND M.MISJA_ID_MOJE_PK <> 123456789
  AND (m.STATUS_MISJI IS NULL OR m.STATUS_MISJI <> 3)
  AND (M.WSKAZNIK_ZGODNOSCI > 0.70000 OR M.WSKAZNIK_ZGODNOSCI IS NULL)
  AND M.DODATEK_EN = 'Midnight'
GROUP BY M.NAZWA_LINII_FABULARNEJ_EN
ORDER BY CNT DESC
;

-- COUNT NA KRAINA
SELECT
	M.KRAINA_EN, COUNT(DISTINCT M.MISJA_ID_Z_GRY) AS CNT
FROM dbo.MISJE AS M
INNER JOIN dbo.ARCHIWUM_MISJE_DIALOGI AS AMD
  ON M.MISJA_ID_Z_GRY = AMD.MISJA_ID_Z_GRY
 AND M.MISJA_ID_MOJE_PK <> 123456789
WHERE M.WSKAZNIK_ZGODNOSCI > 0.70000
GROUP BY M.KRAINA_EN
ORDER BY CNT DESC
;

-- COUNT NA DODATEK
SELECT
	M.DODATEK_EN, COUNT(DISTINCT M.MISJA_ID_Z_GRY) AS CNT
FROM dbo.MISJE AS M
INNER JOIN dbo.ARCHIWUM_MISJE_DIALOGI AS AMD
  ON M.MISJA_ID_Z_GRY = AMD.MISJA_ID_Z_GRY
 AND M.MISJA_ID_MOJE_PK <> 123456789
WHERE M.WSKAZNIK_ZGODNOSCI > 0.70000
GROUP BY M.DODATEK_EN
ORDER BY CNT DESC
;