DECLARE @FILTR_DODATEK NVARCHAR(55) = NULL;
DECLARE @FILTR_FABULA  NVARCHAR(255) = NULL;
DECLARE @FILTR_KRAINA  NVARCHAR(155) = NULL;

DROP TABLE IF EXISTS #MISJE_DO_TLUMACZENIA;

WITH BAZA AS (
    SELECT
        m.MISJA_ID_MOJE_PK,
        m.DODATEK_EN,
        m.NAZWA_LINII_FABULARNEJ_EN,
        m.KRAINA_EN,
        m.STATUS_MISJI,
        m.WSKAZNIK_ZGODNOSCI,
        CASE
            WHEN EXISTS (
                SELECT 1
                FROM dbo.ARCHIWUM_MISJE_DIALOGI AS a
                WHERE a.MISJA_ID_Z_GRY = m.MISJA_ID_Z_GRY
                  AND a.STATUS IN (N'2_ZREDAGOWANO', N'3_ZATWIERDZONO')
            ) THEN 1
            ELSE 0
        END AS MA_ARCHIWUM_2_3
    FROM dbo.MISJE AS m
    WHERE m.MISJA_ID_MOJE_PK <> 123456789
),
KLASYFIKACJA AS (
    SELECT
        *,
        CASE
            WHEN STATUS_MISJI = 2
             AND (
                    MA_ARCHIWUM_2_3 = 0
                    OR WSKAZNIK_ZGODNOSCI <= 0.70000
                    OR WSKAZNIK_ZGODNOSCI IS NULL
                 )
            THEN 1
            ELSE 0
        END AS CZY_A_AI,
        CASE
            WHEN WSKAZNIK_ZGODNOSCI > 0.70000
             AND MA_ARCHIWUM_2_3 = 1
             AND (STATUS_MISJI IS NULL OR STATUS_MISJI <> 3)
            THEN 1
            ELSE 0
        END AS CZY_B_RECZNY
    FROM BAZA
)
SELECT
    MISJA_ID_MOJE_PK,
    DODATEK_EN,
    NAZWA_LINII_FABULARNEJ_EN,
    KRAINA_EN,
    CZY_A_AI,
    CZY_B_RECZNY,
    CASE
        WHEN CZY_A_AI = 1 THEN N'A_AI'
        WHEN CZY_B_RECZNY = 1 THEN N'B_RECZNY'
    END AS WARIANT
INTO #MISJE_DO_TLUMACZENIA
FROM KLASYFIKACJA
WHERE (CZY_A_AI = 1 OR CZY_B_RECZNY = 1)
  AND (@FILTR_DODATEK IS NULL OR DODATEK_EN = @FILTR_DODATEK)
  AND (@FILTR_FABULA IS NULL OR NAZWA_LINII_FABULARNEJ_EN = @FILTR_FABULA)
  AND (@FILTR_KRAINA IS NULL OR KRAINA_EN = @FILTR_KRAINA)
;

IF EXISTS (
    SELECT 1
    FROM #MISJE_DO_TLUMACZENIA
    WHERE CZY_A_AI = 1
      AND CZY_B_RECZNY = 1
)
    THROW 51000, N'Błąd klasyfikacji: co najmniej jedna misja należy jednocześnie do A i B.', 1;

-- 1. PODSUMOWANIE CAŁOŚCI
SELECT
    CASE
        WHEN GROUPING(WARIANT) = 1 THEN N'RAZEM'
        ELSE WARIANT
    END AS WARIANT,
    COUNT(*) AS LICZBA_MISJI
FROM #MISJE_DO_TLUMACZENIA
GROUP BY GROUPING SETS ((WARIANT), ())
ORDER BY
    CASE WHEN GROUPING(WARIANT) = 1 THEN 1 ELSE 0 END,
    WARIANT
;

-- 2. COUNT NA DODATEK
SELECT
    COALESCE(DODATEK_EN, N'(brak dodatku)') AS DODATEK_EN,
    WARIANT,
    COUNT(*) AS LICZBA_MISJI
FROM #MISJE_DO_TLUMACZENIA
GROUP BY DODATEK_EN, WARIANT
ORDER BY LICZBA_MISJI DESC, DODATEK_EN, WARIANT
;

-- 3. COUNT NA FABUŁĘ
SELECT
    COALESCE(NAZWA_LINII_FABULARNEJ_EN, N'(brak linii fabularnej)') AS NAZWA_LINII_FABULARNEJ_EN,
    WARIANT,
    COUNT(*) AS LICZBA_MISJI
FROM #MISJE_DO_TLUMACZENIA
GROUP BY NAZWA_LINII_FABULARNEJ_EN, WARIANT
ORDER BY LICZBA_MISJI DESC, NAZWA_LINII_FABULARNEJ_EN, WARIANT
;

-- 4. COUNT NA KRAINĘ
SELECT
    COALESCE(KRAINA_EN, N'(brak krainy)') AS KRAINA_EN,
    WARIANT,
    COUNT(*) AS LICZBA_MISJI
FROM #MISJE_DO_TLUMACZENIA
GROUP BY KRAINA_EN, WARIANT
ORDER BY LICZBA_MISJI DESC, KRAINA_EN, WARIANT
;

-- 5. COUNT NA PEŁNĄ KOMBINACJĘ: DODATEK + FABUŁA + KRAINA
SELECT
    COALESCE(DODATEK_EN, N'(brak dodatku)') AS DODATEK_EN,
    COALESCE(NAZWA_LINII_FABULARNEJ_EN, N'(brak linii fabularnej)') AS NAZWA_LINII_FABULARNEJ_EN,
    COALESCE(KRAINA_EN, N'(brak krainy)') AS KRAINA_EN,
    WARIANT,
    COUNT(*) AS LICZBA_MISJI
FROM #MISJE_DO_TLUMACZENIA
GROUP BY
    DODATEK_EN,
    NAZWA_LINII_FABULARNEJ_EN,
    KRAINA_EN,
    WARIANT
ORDER BY
    LICZBA_MISJI DESC,
    DODATEK_EN,
    NAZWA_LINII_FABULARNEJ_EN,
    KRAINA_EN,
    WARIANT
;

DROP TABLE IF EXISTS #MISJE_DO_TLUMACZENIA;
