--DELETE FROM dbo.DIALOGI_STATUSY
--WHERE MISJA_ID_MOJE_FK = 150;

--DELETE FROM dbo.MISJE_STATUSY
--WHERE MISJA_ID_MOJE_FK = 150;

--DELETE FROM dbo.ZRODLO_MISJE
--WHERE MISJA_ID_MOJE_FK = 150;

--DELETE FROM dbo.MISJE
--WHERE MISJA_ID_MOJE_PK = 150;

--DELETE FROM dbo.MISJE_STATUSY
--WHERE STATUS = '1_PRZET£UMACZONO'
--   OR STATUS = '2_ZREDAGOWANO';

--DELETE FROM dbo.DIALOGI_STATUSY
--WHERE STATUS = '1_PRZET£UMACZONO'
--   OR STATUS = '2_ZREDAGOWANO';


--DELETE FROM dbo.MISJE_STATUSY
--WHERE MISJA_ID_MOJE_FK = 76
--  AND STATUS IN ('1_PRZET£UMACZONO', '2_ZREDAGOWANO');

--DELETE FROM dbo.DIALOGI_STATUSY
--WHERE MISJA_ID_MOJE_FK = 76
--  AND STATUS IN ('1_PRZET£UMACZONO', '2_ZREDAGOWANO');

DELETE FROM dbo.MISJE_STATUSY
WHERE STATUS = '3_ZATWIERDZONO'
;

DELETE FROM dbo.DIALOGI_STATUSY
WHERE STATUS = '3_ZATWIERDZONO'
;