SELECT 'MISJE', *
FROM dbo.MISJE
WHERE 1=1
  AND STATUS_MISJI = 2
  --AND NAZWA_LINII_FABULARNEJ_EN = 'Path of de Hash''ey'
  --AND DODANO_W_PATCHU = '12.0.1'
  --AND MISJA_TYTUL_EN = 'The Nethersent'
  --AND MISJA_ID_Z_GRY != 123456789
  --AND DODATEK_EN = 'Midnight'
  --AND MISJA_ID_Z_GRY = 90959
  AND MISJA_ID_MOJE_PK /*IN (129, 130, 131)*/ = 8852
  --AND KRAINA_EN = 'Exile''s Reach'
  --AND MISJA_URL_WIKI = 'https://warcraft.wiki.gg/wiki/A_Hunter%27s_Trap_(Horde)'
  AND NPC_KONIEC_ID = 91
;

SELECT 'MISJE_STATUSY', ms.*
FROM dbo.MISJE_STATUSY AS ms
INNER JOIN dbo.MISJE AS m
  ON ms.MISJA_ID_MOJE_FK = m.MISJA_ID_MOJE_PK
WHERE 1=1
  AND m.MISJA_ID_MOJE_PK = 2143
  --AND m.MISJA_TYTUL_EN = 'Heart of the Amani'
  AND m.NAZWA_LINII_FABULARNEJ_EN = 'The Path of Light'
  --AND ms.STATUS = '3_ZATWIERDZONO'
  --AND m.KRAINA_EN = 'Exile''s Reach'
;

SELECT COUNT(DISTINCT MISJA_ID_MOJE_FK)
FROM dbo.MISJE_STATUSY
WHERE STATUS = '3_ZATWIERDZONO'
;

SELECT 'NPC', *
FROM dbo.NPC
WHERE RASA = 'Gnarldin'
ORDER BY NAZWA DESC
;

SELECT 'NPC_STATUSY', *
FROM dbo.NPC_STATUSY
WHERE NPC_ID_FK = 2
;

SELECT 'DIALOGI_STATUSY', ds.*
FROM dbo.DIALOGI_STATUSY AS ds
/*WHERE TRESC LIKE '%the Alliance had best get used tae%'*/
INNER JOIN dbo.MISJE AS m
  ON ds.MISJA_ID_MOJE_FK = m.MISJA_ID_MOJE_PK
WHERE 1=1
  --AND m.KRAINA_EN = 'Exile''s Reach'
  AND m.MISJA_ID_MOJE_PK = 8852
;

SELECT 'ZRODLO_MISJE', *
FROM dbo.ZRODLO_MISJE
WHERE MISJA_ID_MOJE_FK = 1
;

SELECT 'URLE', *
FROM dbo.LINKI_DO_SCRAPOWANIA
;

SELECT 'SLOWA_KLUCZOWE', *
FROM dbo.MISJE_SLOWA_KLUCZOWE
WHERE MISJA_ID_MOJE_FK = 8670
;

SELECT 'MISJE_SLOWA_KLUCZOWE', *
FROM dbo.MISJE_SLOWA_KLUCZOWE
;

SELECT COUNT(MISJA_ID_MOJE_PK) AS CNT
FROM dbo.MISJE
WHERE STATUS_MISJI = 3
  AND MISJA_ID_Z_GRY <> 123456789
