USE WoW_PL
;

CREATE TABLE dbo.ARCHIWUM_MISJE_DIALOGI (
    TECH_ID BIGINT IDENTITY(1, 1) NOT NULL,

    TABELA VARCHAR(30)    NOT NULL
        CHECK (TABELA IN ('MISJE_STATUSY', 'DIALOGI_STATUSY')),

    MISJA_ID_Z_GRY BIGINT     NULL,

    SEGMENT NVARCHAR(30)  NOT NULL
        CHECK (
            SEGMENT IN (
                N'TYTUŁ', N'CEL', N'TREŚĆ', N'POSTĘP',
                N'ZAKOŃCZENIE', N'NAGRODY', N'DYMEK', N'GOSSIP'
                )
        ),

    PODSEGMENT NVARCHAR(30) NULL
        CHECK (PODSEGMENT IN (N'GŁÓWNY_CEL', N'PODRZĘDNY_CEL')),

    STATUS NVARCHAR(30) NOT NULL
        CHECK (STATUS IN (N'0_ORYGINAŁ', N'1_PRZETŁUMACZONO', N'2_ZREDAGOWANO', N'3_ZATWIERDZONO', N'4_REFERENCJA')),

    NR INT              NOT NULL,
    NR_WYPOWIEDZI INT       NULL,
    NPC_ID_FK BIGINT        NULL,
    TRESC NVARCHAR(MAX)     NULL,

    POWOD_ARCHIWIZACJI NVARCHAR(100) NULL DEFAULT 'Zmiana w Wiki',
    DATA_ARCHIWIZACJI DATETIME2  NOT NULL  DEFAULT SYSDATETIME(),


    CONSTRAINT PK_ARCHIWUM PRIMARY KEY (TECH_ID),

    CONSTRAINT CK_ARCHIWUM_PODSEGMENT
        CHECK (
            (SEGMENT = N'CEL'  AND PODSEGMENT IS NOT NULL)
            OR
            (SEGMENT <> N'CEL' AND PODSEGMENT IS     NULL)
        )
)
;

CREATE INDEX IX_ARCHIWUM
ON dbo.ARCHIWUM_MISJE_DIALOGI (MISJA_ID_Z_GRY, TABELA, SEGMENT, PODSEGMENT, NR, NR_WYPOWIEDZI)
;