CREATE TABLE dbo.AI_LOGI (
    AI_LOG_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ANSWER_ID NVARCHAR(255) NULL,
    PROVIDER NVARCHAR(100) NULL,
    SERVICE_TIER NVARCHAR(100) NULL,
    STAGE NVARCHAR(50) NOT NULL
        CONSTRAINT CK_AI_LOGI_STAGE
        CHECK (STAGE IN (
            N'translator',
            N'translator_json_correction',
            N'editor',
            N'editor_json_correction',
            N'rag_questions',
            N'rag_context',
            N'quest_summary'
        )),
    STATUS NVARCHAR(50) NULL,
    DURATION_S DECIMAL(12,4) NULL,
    MISJA_ID_MOJE_FK BIGINT NULL,
    CREATED_AT DATETIME2(3) NULL,
    MODEL NVARCHAR(150) NULL,
    MODEL_API NVARCHAR(150) NULL,
    TOTAL_TOKENS INT NULL,
    INPUT_TOKENS INT NULL,
    OUTPUT_TOKENS INT NULL,
    INPUT_TOKENS_PRICE DECIMAL(18,8) NULL,
    OUTPUT_TOKENS_PRICE DECIMAL(18,8) NULL,
    CURRENCY NVARCHAR(10) NULL,
    CACHED_TOKENS INT NULL,
    THINKING_TOKENS INT NULL,
    INPUT_CHARS_ONLY_JSON INT NULL,
    OUTPUT_CHARS_ONLY_JSON INT NULL,
    REASONING_EFFORT NVARCHAR(50) NULL,
    TEMPERATURE_FROM_LLM DECIMAL(6,3) NULL,
    TEMPERATURE_FROM_CONST DECIMAL(6,3) NULL,
    PARSING_ERROR NVARCHAR(1000) NULL,
    INPUT_SKOMPRESOWANY VARCHAR(MAX) NULL,
    OUTPUT_SKOMPRESOWANY VARCHAR(MAX) NULL,
    CONSTRAINT FK_AI_LOGI_MISJE
        FOREIGN KEY (MISJA_ID_MOJE_FK) REFERENCES dbo.MISJE(MISJA_ID_MOJE_PK)
);
GO

CREATE NONCLUSTERED INDEX IX_AI_LOGI_MISJA_ID_MOJE_FK
ON dbo.AI_LOGI (MISJA_ID_MOJE_FK);
GO
