USE WoW_PL
;

CREATE TABLE dbo.ZRODLO_RAG (
  TECH_ID BIGINT IDENTITY(1, 1)  NOT NULL
    CONSTRAINT PK_ZRODLO_RAG PRIMARY KEY,

  DOC_ID NVARCHAR(200)           NOT NULL,

  BODY_HASH VARCHAR(64)          NOT NULL,
  BODY_WORDS INT                 NULL,
  ZRODLO_NAZWA NVARCHAR(20)      NOT NULL,

  STATUS NVARCHAR(30)            NOT NULL,

  DATA_WYSCRAPOWANIA DATETIME2   NOT NULL DEFAULT SYSDATETIME()
)
;

CREATE INDEX IX_ZRODLO_RAG_DOC_ID_DATA
  ON dbo.ZRODLO_RAG (DOC_ID, DATA_WYSCRAPOWANIA DESC)
  INCLUDE (BODY_HASH, BODY_WORDS)
;