CREATE TABLE dbo.ZRODLO_QDRANT (
    TECH_ID BIGINT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_ZRODLO_QDRANT PRIMARY KEY,

    DOC_ID VARCHAR(255) NOT NULL,
    BODY_HASH VARCHAR(64) NOT NULL,

    STATUS VARCHAR(30) NOT NULL,
    -- np. pending / deleted_old / upserted / skipped / error

    DATA_OPERACJI DATETIME2(0) NOT NULL
        CONSTRAINT DF_ZRODLO_QDRANT_DATA_OPERACJI DEFAULT SYSDATETIME(),

    EMBEDDING_MODEL VARCHAR(255) NOT NULL,
    COLLECTION_NAME VARCHAR(255) NOT NULL,

    ILE_CHUNKOW INT NULL,
    ERROR_MESSAGE NVARCHAR(max) NULL
);

CREATE UNIQUE INDEX UX_ZRODLO_QDRANT_SUKCES
ON dbo.ZRODLO_QDRANT (
    DOC_ID,
    BODY_HASH,
    EMBEDDING_MODEL,
    COLLECTION_NAME
)
WHERE STATUS = 'upserted';