USE WoW_PL
;

CREATE TABLE dbo.MISJE_PODSUMOWANIA (
  TECH_ID BIGINT IDENTITY(1, 1)     NOT NULL,

  MISJA_ID_MOJE_FK BIGINT           NOT NULL,
  MISJA_ID_Z_GRY BIGINT             NULL,

  PODSUMOWANIE NVARCHAR(1000)       NOT NULL,

  DATA_DODANIA DATETIME2(0)         NOT NULL
    CONSTRAINT DF_MISJE_PODSUMOWANIA_DATA_DODANIA
    DEFAULT SYSDATETIME(),

  DATA_AKTUALIZACJI DATETIME2(0)    NOT NULL
    CONSTRAINT DF_MISJE_PODSUMOWANIA_DATA_AKTUALIZACJI
    DEFAULT SYSDATETIME(),

  CONSTRAINT PK_MISJE_PODSUMOWANIA
    PRIMARY KEY CLUSTERED (TECH_ID),

  CONSTRAINT FK_MISJE_PODSUMOWANIA_MISJE
    FOREIGN KEY (MISJA_ID_MOJE_FK)
    REFERENCES dbo.MISJE (MISJA_ID_MOJE_PK),

  CONSTRAINT UQ_MISJE_PODSUMOWANIA_MISJA
    UNIQUE (MISJA_ID_MOJE_FK)
)
;

CREATE INDEX IX_MISJE_PODSUMOWANIA_MISJA
ON dbo.MISJE_PODSUMOWANIA (MISJA_ID_MOJE_FK)
;
GO

CREATE TRIGGER trg_MISJE_PODSUMOWANIA_DATAUPDATE
ON dbo.MISJE_PODSUMOWANIA
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE p
    SET DATA_AKTUALIZACJI = SYSDATETIME()
    FROM dbo.MISJE_PODSUMOWANIA AS p
    INNER JOIN inserted AS i
        ON p.TECH_ID = i.TECH_ID;
END
GO
