USE WoW_PL
;

CREATE TABLE dbo.GEMINI_BATCH_REDAKTOR_JOBY (
    JOB_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    JOB_NAME NVARCHAR(255) NOT NULL,
    MODEL NVARCHAR(150) NOT NULL,
    DISPLAY_NAME NVARCHAR(255) NULL,
    INPUT_FILE_NAME NVARCHAR(255) NULL,
    INPUT_FILE_PATH NVARCHAR(1000) NULL,
    OUTPUT_FILE_NAME NVARCHAR(255) NULL,
    OUTPUT_FILE_PATH NVARCHAR(1000) NULL,
    STATUS NVARCHAR(50) NOT NULL,
    STATE NVARCHAR(80) NULL,
    CREATED_AT DATETIME2(3) NOT NULL
        CONSTRAINT DF_GEMINI_BATCH_REDAKTOR_JOBY_CREATED_AT DEFAULT SYSDATETIME(),
    UPDATED_AT DATETIME2(3) NOT NULL
        CONSTRAINT DF_GEMINI_BATCH_REDAKTOR_JOBY_UPDATED_AT DEFAULT SYSDATETIME(),
    LICZBA_POZYCJI INT NOT NULL
        CONSTRAINT DF_GEMINI_BATCH_REDAKTOR_JOBY_LICZBA_POZYCJI DEFAULT 0,
    SAVED_COUNT INT NOT NULL
        CONSTRAINT DF_GEMINI_BATCH_REDAKTOR_JOBY_SAVED_COUNT DEFAULT 0,
    FAILED_COUNT INT NOT NULL
        CONSTRAINT DF_GEMINI_BATCH_REDAKTOR_JOBY_FAILED_COUNT DEFAULT 0,
    ERROR_TXT NVARCHAR(2000) NULL,

    CONSTRAINT UQ_GEMINI_BATCH_REDAKTOR_JOBY_JOB_NAME UNIQUE (JOB_NAME)
)
;

CREATE NONCLUSTERED INDEX IX_GEMINI_BATCH_REDAKTOR_JOBY_STATUS
ON dbo.GEMINI_BATCH_REDAKTOR_JOBY (STATUS, CREATED_AT)
;

CREATE TABLE dbo.GEMINI_BATCH_REDAKTOR_POZYCJE (
    ITEM_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    JOB_NAME NVARCHAR(255) NOT NULL,
    REQUEST_KEY NVARCHAR(120) NOT NULL,
    MISJA_ID_MOJE_FK BIGINT NOT NULL,
    STATUS NVARCHAR(50) NOT NULL
        CONSTRAINT DF_GEMINI_BATCH_REDAKTOR_POZYCJE_STATUS DEFAULT N'SUBMITTED',
    WSAD_JSON_SKOMPRESOWANY VARCHAR(MAX) NULL,
    PROMPT_SKOMPRESOWANY VARCHAR(MAX) NULL,
    OUTPUT_SKOMPRESOWANY VARCHAR(MAX) NULL,
    ERROR_TXT NVARCHAR(2000) NULL,
    INPUT_TOKENS INT NULL,
    OUTPUT_TOKENS INT NULL,
    TOTAL_TOKENS INT NULL,
    CREATED_AT DATETIME2(3) NOT NULL
        CONSTRAINT DF_GEMINI_BATCH_REDAKTOR_POZYCJE_CREATED_AT DEFAULT SYSDATETIME(),
    UPDATED_AT DATETIME2(3) NOT NULL
        CONSTRAINT DF_GEMINI_BATCH_REDAKTOR_POZYCJE_UPDATED_AT DEFAULT SYSDATETIME(),

    CONSTRAINT UQ_GEMINI_BATCH_REDAKTOR_POZYCJE_JOB_KEY UNIQUE (JOB_NAME, REQUEST_KEY),
    CONSTRAINT FK_GEMINI_BATCH_REDAKTOR_POZYCJE_JOB
        FOREIGN KEY (JOB_NAME) REFERENCES dbo.GEMINI_BATCH_REDAKTOR_JOBY(JOB_NAME),
    CONSTRAINT FK_GEMINI_BATCH_REDAKTOR_POZYCJE_MISJE
        FOREIGN KEY (MISJA_ID_MOJE_FK) REFERENCES dbo.MISJE(MISJA_ID_MOJE_PK)
)
;

CREATE NONCLUSTERED INDEX IX_GEMINI_BATCH_REDAKTOR_POZYCJE_JOB
ON dbo.GEMINI_BATCH_REDAKTOR_POZYCJE (JOB_NAME, STATUS)
;

CREATE NONCLUSTERED INDEX IX_GEMINI_BATCH_REDAKTOR_POZYCJE_MISJA
ON dbo.GEMINI_BATCH_REDAKTOR_POZYCJE (MISJA_ID_MOJE_FK)
;
