USE WoW_PL
;

CREATE TABLE dbo.ZRODLO_MISJE (
  TECH_ID BIGINT IDENTITY(1, 1)      NOT NULL,

  MISJA_ID_MOJE_FK BIGINT            NOT NULL,

  ZRODLO_NAZWA NVARCHAR(20)          NOT NULL
    CHECK (ZRODLO_NAZWA IN (N'wiki', N'wowhead', N'wowdb', N'recznie', N'z addonu')),

  RODZAJ NVARCHAR(20)                NOT NULL DEFAULT N'MISJA',

  DATA_WYSCRAPOWANIA DATETIME2  NOT NULL DEFAULT SYSDATETIME(),

  HTML_HASH_GLOWNY_CEL CHAR(64)     NULL,
  HTML_HASH_PODRZEDNY_CEL CHAR(64)  NULL,
  HTML_HASH_TRESC CHAR(64)          NULL,
  HTML_HASH_POSTEP CHAR(64)         NULL,
  HTML_HASH_ZAKONCZENIE CHAR(64)    NULL,
  HTML_HASH_NAGRODY CHAR(64)        NULL,
  HTML_HASH_DYMKI CHAR(64)          NULL,
  HTML_HASH_GOSSIP CHAR(64)         NULL,
  HTML_SKOMPRESOWANY VARCHAR(MAX)   NULL,

  CONSTRAINT PK_ZRODLO_MISJE PRIMARY KEY (TECH_ID),

  CONSTRAINT FK_ZRODLO_MISJE_MISJE
    FOREIGN KEY (MISJA_ID_MOJE_FK) REFERENCES dbo.MISJE(MISJA_ID_MOJE_PK)
)
;

CREATE INDEX IX_ZRODLO_MISJE_MISJA
ON dbo.ZRODLO_MISJE (MISJA_ID_MOJE_FK, DATA_WYSCRAPOWANIA DESC)
;
